export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"17 TheWord 文档库"},["/index.html","/README.md"]],
  ["v-4c04e6ac","/api/image.html",{"title":"随机图片"},["/api/image","/api/image.md"]],
  ["v-b2bd48e6","/api/lolrecord.html",{"title":"随机LOL英雄语音"},["/api/lolrecord","/api/lolrecord.md"]],
  ["v-744497ce","/api/",{"title":"介绍"},["/api/index.html","/api/README.md"]],
  ["v-33f4d5ee","/haruka_guild/install.html",{"title":"使用方法"},["/haruka_guild/install","/haruka_guild/install.md"]],
  ["v-77c8ac60","/haruka_guild/",{"title":"介绍"},["/haruka_guild/index.html","/haruka_guild/README.md"]],
  ["v-e2bd9c40","/haruka_guild/update.html",{"title":"更新 & 问题记录"},["/haruka_guild/update","/haruka_guild/update.md"]],
  ["v-c234e7c2","/mchelp/",{"title":"前言"},["/mchelp/index.html","/mchelp/README.md"]],
  ["v-204d3ecb","/mc_qq/about.html",{"title":"关于"},["/mc_qq/about","/mc_qq/about.md"]],
  ["v-2edc9d50","/mc_qq/config.html",{"title":"配置"},["/mc_qq/config","/mc_qq/config.md"]],
  ["v-ed8567c2","/mc_qq/",{"title":"前言"},["/mc_qq/index.html","/mc_qq/README.md"]],
  ["v-754f4f9e","/mc_qq/update.html",{"title":"更新记录"},["/mc_qq/update","/mc_qq/update.md"]],
  ["v-5d52e5fc","/mgc/author_says.html",{"title":"作者有话说"},["/mgc/author_says","/mgc/author_says.md"]],
  ["v-73d40dc5","/mgc/mistakes.html",{"title":"光线追踪误区"},["/mgc/mistakes","/mgc/mistakes.md"]],
  ["v-7da9167e","/mgc/netease_shader.html",{"title":"网易版着色器"},["/mgc/netease_shader","/mgc/netease_shader.md"]],
  ["v-c6709a70","/mgc/other.html",{"title":"其他观点纠正"},["/mgc/other","/mgc/other.md"]],
  ["v-7449e9bf","/mgc/",{"title":"导言"},["/mgc/index.html","/mgc/README.md"]],
  ["v-80764dc4","/mchelp/install/download.html",{"title":"正版获取及下载"},["/mchelp/install/download","/mchelp/install/download.md"]],
  ["v-6464732a","/mchelp/install/mod.html",{"title":"安装 Mod"},["/mchelp/install/mod","/mchelp/install/mod.md"]],
  ["v-b7bb6234","/mchelp/install/package.html",{"title":"安装整合包"},["/mchelp/install/package","/mchelp/install/package.md"]],
  ["v-357456c6","/mchelp/install/shadow.html",{"title":"安装光影与材质"},["/mchelp/install/shadow","/mchelp/install/shadow.md"]],
  ["v-694fcc4f","/mchelp/introduce/",{"title":"简介"},["/mchelp/introduce/index.html","/mchelp/introduce/README.md"]],
  ["v-d762f608","/mchelp/online/multiplayer.html",{"title":"多人联机"},["/mchelp/online/multiplayer","/mchelp/online/multiplayer.md"]],
  ["v-23a097ce","/mchelp/online/server.html",{"title":"开服部分"},["/mchelp/online/server","/mchelp/online/server.md"]],
  ["v-8cc99a98","/mchelp/other/another.html",{"title":"其他的细节"},["/mchelp/other/another","/mchelp/other/another.md"]],
  ["v-77d02dd6","/mchelp/other/mod.html",{"title":"Mod 冲突解决方法"},["/mchelp/other/mod","/mchelp/other/mod.md"]],
  ["v-f94ac0b0","/mchelp/other/online.html",{"title":"关于MC正版的那些事"},["/mchelp/other/online","/mchelp/other/online.md"]],
  ["v-b115ff9e","/mchelp/other/shadow_material.html",{"title":"光影与材质基础概念"},["/mchelp/other/shadow_material","/mchelp/other/shadow_material.md"]],
  ["v-1025a7d7","/mchelp/resource/launcher.html",{"title":"启动器下载区"},["/mchelp/resource/launcher","/mchelp/resource/launcher.md"]],
  ["v-0d3caeb0","/mchelp/resource/material.html",{"title":"材质包下载区"},["/mchelp/resource/material","/mchelp/resource/material.md"]],
  ["v-adf5648e","/mchelp/resource/mod.html",{"title":"Mod下载区"},["/mchelp/resource/mod","/mchelp/resource/mod.md"]],
  ["v-090d4884","/mchelp/resource/online.html",{"title":"联机下载区"},["/mchelp/resource/online","/mchelp/resource/online.md"]],
  ["v-beb56c16","/mchelp/resource/package.html",{"title":"整合包下载区"},["/mchelp/resource/package","/mchelp/resource/package.md"]],
  ["v-dfa38452","/mchelp/resource/shadow.html",{"title":"光影下载区"},["/mchelp/resource/shadow","/mchelp/resource/shadow.md"]],
  ["v-6507c540","/mc_qq/install/mcrcon.html",{"title":"MCRcon + 日志读取安装"},["/mc_qq/install/mcrcon","/mc_qq/install/mcrcon.md"]],
  ["v-033e7d00","/mc_qq/install/mcrcon_plugin.html",{"title":"MCRcon + 插件安装"},["/mc_qq/install/mcrcon_plugin","/mc_qq/install/mcrcon_plugin.md"]],
  ["v-4d9116da","/mc_qq/install/plugin.html",{"title":"插件安装"},["/mc_qq/install/plugin","/mc_qq/install/plugin.md"]],
  ["v-62914b13","/mc_qq/install/",{"title":"选择安装方式"},["/mc_qq/install/index.html","/mc_qq/install/README.md"]],
  ["v-6668df24","/mgc/qas/shadow.html",{"title":"光影篇"},["/mgc/qas/shadow","/mgc/qas/shadow.md"]],
  ["v-0df5e689","/mgc/qas/texture.html",{"title":"纹理包篇"},["/mgc/qas/texture","/mgc/qas/texture.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
