<template><div><p>创建 wjk 项目：</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>openstack project <span class="token keyword">create</span> <span class="token comment">--domain default --description "wjk Project" wjk</span>
<span class="token operator">+</span><span class="token comment">-------------+----------------------------------+</span>
<span class="token operator">|</span> Field       <span class="token operator">|</span> <span class="token keyword">Value</span>                            <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">-------------+----------------------------------+</span>
<span class="token operator">|</span> description <span class="token operator">|</span> wjk Project                    <span class="token operator">|</span>
<span class="token operator">|</span> domain_id   <span class="token operator">|</span> <span class="token keyword">default</span>                          <span class="token operator">|</span>
<span class="token operator">|</span> enabled     <span class="token operator">|</span> <span class="token boolean">True</span>                             <span class="token operator">|</span>
<span class="token operator">|</span> id          <span class="token operator">|</span> <span class="token number">343</span>d245e850143a096806dfaefa9afdc <span class="token operator">|</span>
<span class="token operator">|</span> is_domain   <span class="token operator">|</span> <span class="token boolean">False</span>                            <span class="token operator">|</span>
<span class="token operator">|</span> name        <span class="token operator">|</span> wjk                            <span class="token operator">|</span>
<span class="token operator">|</span> parent_id   <span class="token operator">|</span> None                             <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">-------------+----------------------------------+</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>创建 wjk 用户：</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>openstack <span class="token keyword">user</span> <span class="token keyword">create</span> <span class="token comment">--domain default --password-prompt wjk</span>
<span class="token keyword">User</span> Password: wjk123
<span class="token keyword">Repeat</span> <span class="token keyword">User</span> Password: wjk123
<span class="token operator">+</span><span class="token comment">-----------+----------------------------------+</span>
<span class="token operator">|</span> Field     <span class="token operator">|</span> <span class="token keyword">Value</span>                            <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">-----------+----------------------------------+</span>
<span class="token operator">|</span> domain_id <span class="token operator">|</span> <span class="token keyword">default</span>                          <span class="token operator">|</span>
<span class="token operator">|</span> enabled   <span class="token operator">|</span> <span class="token boolean">True</span>                             <span class="token operator">|</span>
<span class="token operator">|</span> id        <span class="token operator">|</span> ac3377633149401296f6c0d92d79dc16 <span class="token operator">|</span>
<span class="token operator">|</span> name      <span class="token operator">|</span> wjk                            <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">-----------+----------------------------------+</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>添加<code v-pre>wjk</code> 角色到 wjk 项目和用户上：</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>openstack role <span class="token keyword">add</span> <span class="token comment">--project wjk --user wjk</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>创建镜像</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>glance image<span class="token operator">-</span><span class="token keyword">create</span> <span class="token comment">--name "wjk" \</span>
  <span class="token comment">--file cirros-0.3.4-x86_64-disk.img \</span>
  <span class="token comment">--disk-format qcow2 --container-format bare \</span>
  <span class="token comment">--visibility public --progress</span>
<span class="token punctuation">[</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">=</span><span class="token operator">></span><span class="token punctuation">]</span> <span class="token number">100</span><span class="token operator">%</span>
<span class="token operator">+</span><span class="token comment">------------------+--------------------------------------+</span>
<span class="token operator">|</span> Property         <span class="token operator">|</span> <span class="token keyword">Value</span>                                <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">------------------+--------------------------------------+</span>
<span class="token operator">|</span> checksum         <span class="token operator">|</span> <span class="token number">133</span>eae9fb1c98f45894a4e60d8736619     <span class="token operator">|</span>
<span class="token operator">|</span> container_format <span class="token operator">|</span> bare                                 <span class="token operator">|</span>
<span class="token operator">|</span> created_at       <span class="token operator">|</span> <span class="token number">2015</span><span class="token operator">-</span><span class="token number">03</span><span class="token operator">-</span><span class="token number">26</span>T16:<span class="token number">52</span>:<span class="token number">10</span>Z                 <span class="token operator">|</span>
<span class="token operator">|</span> disk_format      <span class="token operator">|</span> qcow2                                <span class="token operator">|</span>
<span class="token operator">|</span> id               <span class="token operator">|</span> <span class="token number">38047887</span><span class="token operator">-</span><span class="token number">61</span>a7<span class="token operator">-</span><span class="token number">41</span>ea<span class="token operator">-</span><span class="token number">9</span>b49<span class="token operator">-</span><span class="token number">27987</span>d5e8bb9 <span class="token operator">|</span>
<span class="token operator">|</span> min_disk         <span class="token operator">|</span> <span class="token number">0</span>                                    <span class="token operator">|</span>
<span class="token operator">|</span> min_ram          <span class="token operator">|</span> <span class="token number">0</span>                                    <span class="token operator">|</span>
<span class="token operator">|</span> name             <span class="token operator">|</span> cirros                               <span class="token operator">|</span>
<span class="token operator">|</span> owner            <span class="token operator">|</span> ae7a98326b9c455588edd2656d723b9d     <span class="token operator">|</span>
<span class="token operator">|</span> protected        <span class="token operator">|</span> <span class="token boolean">False</span>                                <span class="token operator">|</span>
<span class="token operator">|</span> size             <span class="token operator">|</span> <span class="token number">13200896</span>                             <span class="token operator">|</span>
<span class="token operator">|</span> <span class="token keyword">status</span>           <span class="token operator">|</span> active                               <span class="token operator">|</span>
<span class="token operator">|</span> tags             <span class="token operator">|</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>                                   <span class="token operator">|</span>
<span class="token operator">|</span> updated_at       <span class="token operator">|</span> <span class="token number">2015</span><span class="token operator">-</span><span class="token number">03</span><span class="token operator">-</span><span class="token number">26</span>T16:<span class="token number">52</span>:<span class="token number">10</span>Z                 <span class="token operator">|</span>
<span class="token operator">|</span> virtual_size     <span class="token operator">|</span> None                                 <span class="token operator">|</span>
<span class="token operator">|</span> visibility       <span class="token operator">|</span> <span class="token keyword">public</span>                               <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">------------------+--------------------------------------+</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>列出镜像</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>nova image<span class="token operator">-</span>list
<span class="token operator">+</span><span class="token comment">-----------------------+---------------------------------+--------+--------------------------+</span>
<span class="token operator">|</span> ID                    <span class="token operator">|</span> Name                            <span class="token operator">|</span> <span class="token keyword">Status</span> <span class="token operator">|</span> Server                   <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">-----------------------+---------------------------------+--------+--------------------------+</span>
<span class="token operator">|</span> <span class="token number">397</span>e713c<span class="token operator">-</span>b95b<span class="token operator">-</span><span class="token number">4186.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token operator">|</span> cirros<span class="token operator">-</span><span class="token number">0.3</span><span class="token number">.2</span><span class="token operator">-</span>x86_64<span class="token operator">-</span>uec         <span class="token operator">|</span> ACTIVE <span class="token operator">|</span>                          <span class="token operator">|</span>
<span class="token operator">|</span> df430cc2<span class="token operator">-</span><span class="token number">3406</span><span class="token operator">-</span><span class="token number">4061.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token operator">|</span> cirros<span class="token operator">-</span><span class="token number">0.3</span><span class="token number">.2</span><span class="token operator">-</span>x86_64<span class="token operator">-</span>uec<span class="token operator">-</span>kernel  <span class="token operator">|</span> ACTIVE <span class="token operator">|</span>                          <span class="token operator">|</span>
<span class="token operator">|</span> <span class="token number">3</span>cf852bd<span class="token operator">-</span><span class="token number">2332</span><span class="token operator">-</span><span class="token number">48</span>f4<span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token operator">|</span> cirros<span class="token operator">-</span><span class="token number">0.3</span><span class="token number">.2</span><span class="token operator">-</span>x86_64<span class="token operator">-</span>uec<span class="token operator">-</span>ramdisk <span class="token operator">|</span> ACTIVE <span class="token operator">|</span>                          <span class="token operator">|</span>
<span class="token operator">|</span> <span class="token number">7</span>e5142af<span class="token operator">-</span><span class="token number">1253</span><span class="token operator">-</span><span class="token number">4634.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token operator">|</span> myCirrosImage                   <span class="token operator">|</span> ACTIVE <span class="token operator">|</span> <span class="token number">84</span>c6e57d<span class="token operator">-</span>a6b1<span class="token operator">-</span><span class="token number">44</span>b6<span class="token operator">-</span><span class="token number">81.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token operator">|</span>
<span class="token operator">|</span> <span class="token number">89</span>bcd424<span class="token operator">-</span><span class="token number">9</span>d15<span class="token operator">-</span><span class="token number">4723.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token operator">|</span> mysnapshot                      <span class="token operator">|</span> ACTIVE <span class="token operator">|</span> f51ebd07<span class="token operator">-</span>c33d<span class="token operator">-</span><span class="token number">4951</span><span class="token operator">-</span><span class="token number">87.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">-----------------------+---------------------------------+--------+--------------------------+</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>列出作用域</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>cinder availability<span class="token operator">-</span>zone<span class="token operator">-</span>list
<span class="token operator">+</span><span class="token comment">------+-----------+</span>
<span class="token operator">|</span> Name <span class="token operator">|</span>   <span class="token keyword">Status</span>  <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">------+-----------+</span>
<span class="token operator">|</span> nova <span class="token operator">|</span> available <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">------+-----------+</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>创建卷</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>cinder <span class="token keyword">create</span> <span class="token number">8</span> <span class="token comment">--display-name wjk-volume --image-id 397e713c-b95b-4186-ad46-6126863ea0a9 --availability-zone nova</span>
<span class="token operator">+</span><span class="token comment">---------------------+--------------------------------------+</span>
<span class="token operator">|</span>       Property      <span class="token operator">|</span>                <span class="token keyword">Value</span>                 <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">---------------------+--------------------------------------+</span>
<span class="token operator">|</span>     attachments     <span class="token operator">|</span>                  <span class="token punctuation">[</span><span class="token punctuation">]</span>                  <span class="token operator">|</span>
<span class="token operator">|</span>  availability_zone  <span class="token operator">|</span>                 nova                 <span class="token operator">|</span>
<span class="token operator">|</span>       bootable      <span class="token operator">|</span>                <span class="token boolean">false</span>                 <span class="token operator">|</span>
<span class="token operator">|</span>      created_at     <span class="token operator">|</span>      <span class="token number">2013</span><span class="token operator">-</span><span class="token number">07</span><span class="token operator">-</span><span class="token number">25</span>T17:<span class="token number">02</span>:<span class="token number">12.472269</span>      <span class="token operator">|</span>
<span class="token operator">|</span> display_description <span class="token operator">|</span>                 None                 <span class="token operator">|</span>
<span class="token operator">|</span>     display_name    <span class="token operator">|</span>               wjk<span class="token operator">-</span>volume             <span class="token operator">|</span>
<span class="token operator">|</span>          id         <span class="token operator">|</span> <span class="token number">573</span>e024d<span class="token operator">-</span><span class="token number">5235</span><span class="token operator">-</span><span class="token number">49</span>ce<span class="token operator">-</span><span class="token number">8332</span><span class="token operator">-</span>be1576d323f8 <span class="token operator">|</span>
<span class="token operator">|</span>       image_id      <span class="token operator">|</span> <span class="token number">397</span>e713c<span class="token operator">-</span>b95b<span class="token operator">-</span><span class="token number">4186</span><span class="token operator">-</span>ad46<span class="token operator">-</span><span class="token number">6126863</span>ea0a9 <span class="token operator">|</span>
<span class="token operator">|</span>       metadata      <span class="token operator">|</span>                  {}                  <span class="token operator">|</span>
<span class="token operator">|</span>         size        <span class="token operator">|</span>                  <span class="token number">8</span>                   <span class="token operator">|</span>
<span class="token operator">|</span>     snapshot_id     <span class="token operator">|</span>                 None                 <span class="token operator">|</span>
<span class="token operator">|</span>     source_volid    <span class="token operator">|</span>                 None                 <span class="token operator">|</span>
<span class="token operator">|</span>        <span class="token keyword">status</span>       <span class="token operator">|</span>               creating               <span class="token operator">|</span>
<span class="token operator">|</span>     volume_type     <span class="token operator">|</span>                 None                 <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">---------------------+--------------------------------------+</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>列出卷</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>cinder list
<span class="token operator">+</span><span class="token comment">-----------------+-----------+-----------------+------+-------------+----------+-------------+</span>
<span class="token operator">|</span>    ID           <span class="token operator">|</span>   <span class="token keyword">Status</span>  <span class="token operator">|</span>   Display Name  <span class="token operator">|</span> Size <span class="token operator">|</span> Volume <span class="token keyword">Type</span> <span class="token operator">|</span> Bootable <span class="token operator">|</span> Attached <span class="token keyword">to</span> <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">-----------------+-----------+-----------------+------+-------------+----------+-------------+</span>
<span class="token operator">|</span> <span class="token number">573</span>e024d<span class="token operator">-</span><span class="token number">523.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> <span class="token operator">|</span> available <span class="token operator">|</span>  wjk<span class="token operator">-</span>volume     <span class="token operator">|</span>  <span class="token number">8</span>   <span class="token operator">|</span>     None    <span class="token operator">|</span>   <span class="token boolean">true</span>   <span class="token operator">|</span>             <span class="token operator">|</span>
<span class="token operator">+</span><span class="token comment">-----------------+-----------+-----------------+------+-------------+----------+-------------+</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>虚拟机操作</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>nova <span class="token keyword">start</span> vm<span class="token operator">-</span>wjk
nova stop vm<span class="token operator">-</span>wjk
nova suspend vm<span class="token operator">-</span>wjk
nova <span class="token keyword">delete</span> vm<span class="token operator">-</span>wjk
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
