name: github pages
  on:
    push:
      branches:
        - main
  jobs:
    build-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - run: npm ci # 相当于npm install
        - run: npm run docs:build

        #发布到mybells.github.io/master
        - name: Deploy mybells.github.io/master
          uses: peaceiris/actions-gh-pages@v2
          env:
            ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            EXTERNAL_REPOSITORY: 17TheWord/17TheWord.github.io #可以新建一个mybells.github.io仓库发布到master
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: docs/.vuepress/dist
          with:
            emptyCommits: false
